name = "BioLizard"
uuid = "b54d7771-5eef-4c20-b8e0-2d53af1051e5"
authors = ["michielstock <michielfmstock@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
